"""Constants for the JingDong XIoT integration."""

DOMAIN = "jd_xiot"
JD_AUTH_TYPE = "auth_type"
JD_AUTH_TYPE_SCREEN = "screen"
JD_AUTH_TYPE_ACCOUNT = "account"
JD_AUTH_TYPE_ACCOUNT_WITH_SIGNATURE = "account-with-signature"
JD_SCREEN_IP = "ip"
JD_COOKIE = "cookie"
JD_WSKEY = "wskey"
JD_SELECTED_HOUSE_ID = "selected_house_id"
JD_SELECTED_DEVICE_IDS = "selected_device_ids"
